name: Build and Release LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest
    env:
      TZ: 'America/Toronto'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build PDF
        run: latexmk -pdf ./notes/main.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CO_631_notes.pdf
          path: ./notes/main.pdf

      - name: Get Current Date and Time
        id: datetime
        run: echo "date=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.datetime.outputs.date }}
          name: Release ${{ steps.datetime.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
